# Generated by Django 3.0.6 on 2020-08-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_add_p_description_and_multiple_p_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='dpto',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='c_i',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='ruc',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
