# Generated by Django 3.0.6 on 2020-08-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_add_field_to_shippingAdress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='c_i',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
